
spring.datasource.url=jdbc:mysql://localhost:3306/frauddb
spring.datasource.username=root
spring.datasource.password=
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.database = MYSQL
spring.jpa.hibernate.ddl-auto= update
server.port= 9000
twilio.account-sid=ACe2ee80d2020d5adf8ed8647da4d4db8d
twilio.auth-token=8527fbb7ce4d1d58df48ecbd6d55cbdd
spring.mvc.throw-exception-if-no-handler-found=true
